--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Blugin/Lifespan
branches:
  - master
projects:
  PaymentPool:
    icon: "icon.png"
    lint:
      phpstan: false
    libs:
      - src: Blugin/libcommand/libcommand
        version: ^1.3.3
      - src: Blugin/libtranslator/libtranslator
        version: ^1.0.5
      - src: Blugin/SingletonTrait/SingletonTrait
        version: ^1.0.0
      - src: Blugin/arrayutils/arrayutils
        version: ^2.0.0
...
