---
name: Lifespan
main: kim\present\lifespan\Lifespan
version: 2.0.0
api: [3.0.0, 4.0.0]
author: PresentKim
description: Set item&arrow's lifespan!

permissions:
  lifespan.cmd:
    description: Lifespan command
    default: op
...