---
name: Lifespan
main: blugin\lifespan\Lifespan
version: 3.0.0
api: [3.0.0]
authors: ['Blugin-team', 'PresentKim']
description: 'Set item and arrow lifespan!'
load: STARTUP

permissions:
  lifespan.cmd:
    description: Lifespan command
    default: op
    children:
      lifespan.cmd.item:
        description: Lifespan command - item
        default: op
      lifespan.cmd.arrow:
        description: Lifespan command - arrow
        default: op
...