---
name:             LifeSpan
main:             presentkim\lifespan\LifeSpan
version:          1.1.1
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author:           PresentKim
website:          https://github.com/PMMPPlugin/LifeSpan
description:      A plugin control item and arrow's lifespan

permissions:
  lifespan.cmd:
    description:  LifeSpan main command
    default:      op
    children:
      lifespan.cmd.item:
        description:  LifeSpan command - item
        default:      op
      lifespan.cmd.arrow:
        description:  LifeSpan command - arrow
        default:      op
      lifespan.cmd.lang:
        description:  LifeSpan command - lang
        default:      op
      lifespan.cmd.reload:
        description:  LifeSpan command - reload
        default:      op
      lifespan.cmd.save:
        description:  LifeSpan command - save
        default:      op
...
