---
name: Lifespan
main: blugin\lifespan\Lifespan
version: 2.0.0
author: PresentKim
description: Set item&arrow's lifespan!
api: [4.0.0]
depend: [libPluginLang]

permissions:
  lifespan.cmd:
    description: Lifespan command
    default: op
...