---
name: Lifespan
main: blugin\lifespan\Lifespan
version: 2.0.0
api: [4.0.0]
authors: ['Blugin-team', 'PresentKim']
description: Set item and arrow's lifespan!
depend: [libPluginLang]

permissions:
  lifespan.cmd:
    description: Lifespan command
    default: op
...