---
name:             LifeSpan
main:             blugin\lifespan\LifeSpan
version:          1.1.2
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author:           PresentKim
website:          https://github.com/Blugin/LifeSpan-PMMP
description:      A plugin control item and arrow's lifespan

permissions:
  lifespan.cmd:
    description:  "Set entity's lifespan"
    default:      op
...
