# Файл продвинутой конфигурации плагина Lifespan
# Некоторые из этих настроек являются безопасными, другие могут сломать ваш сервер, если они изменены неправильно
# Новые настройки / значения по умолчанию не будут отображаться автоматически в этом файле при обновлении
# Translated by @SteinsSquad
# Plugin author @PresentKim

settings:
  #Настройки мульти-язычности
  #Доступно: eng, kor, rus
  language: "rus"

  update-check: false


command:
  #Название комманды
  #Вы можете изменить это так, как захотите
  name: "lifespan"

  #Псевдоним основной комманды
  #Вы можете изменять, удалять, добавлять это так, как захотите
  aliases: ["lifetime", "ls"]

  children:
    #Настройка суб-комманд
    #Также, как с настройкой комманды
    item:
      name: "Item"
      aliases: ["i", "itementity"]
    arrow:
      name: "Arrow"
      aliases: ["a", "arrowentity"]


permission:
  #Право основной комманды
  #Вы можете изменить это так, как захотите
  main: "op"